---
name: 'tfplugindocs'
on:
  pull_request:
permissions:
  contents: read
jobs:
  tfplugindocs:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Get dependencies
        run: go mod download
      - name: Run tfplugindocs
        run: go generate ./...

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Fail if any files changed
        shell: bash
        run: |
          if [[ $(git status --porcelain=v1 | wc -l) -ne 0 ]]; then
            echo "Please ensure tfplugindocs changes are committed"
            echo "Changed files:"
            git diff --name-only
            exit 1
          fi
